from pathlib import Path
import sqlite3
from datetime import datetime
from weasyprint import HTML

DB_PATH = Path("data/orders.db")
OUTPUT_DIR = Path("generated_pdfs")
OUTPUT_DIR.mkdir(exist_ok=True)

def generate_requisition_pdf(requisition_id: int) -> Path:
    # --- Step 1: Get data from DB ---
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    cursor.execute("""
        SELECT r.requisition_number, r.requisition_note, r.requisition_date, rq.name AS requisitioner
        FROM requisitions r
        LEFT JOIN requisitioners rq ON r.requisitioner_id = rq.id
        WHERE r.id = ?
    """, (requisition_id,))
    header = cursor.fetchone()

    if not header:
        raise ValueError("Requisition not found")

    cursor.execute("""
        SELECT description, project, quantity
        FROM requisition_items
        WHERE requisition_id = ?
    """, (requisition_id,))
    items = cursor.fetchall()
    conn.close()

    # --- Step 2: Build HTML ---
    html = f"""
    <html>
    <head>
        <style>
            body {{
                font-family: Arial, sans-serif;
                margin: 2rem;
            }}
            h2 {{
                color: #2a2a2a;
            }}
            table {{
                width: 100%;
                border-collapse: collapse;
                margin-top: 1rem;
            }}
            th, td {{
                border: 1px solid #ccc;
                padding: 8px;
                text-align: left;
            }}
            th {{
                background-color: #f2f2f2;
            }}
        </style>
    </head>
    <body>
        <h2>📦 Requisition PDF</h2>
        <p><strong>Requisition Number:</strong> {header['requisition_number']}</p>
        <p><strong>Requisitioner:</strong> {header['requisitioner']}</p>
        <p><strong>Date:</strong> {datetime.fromisoformat(header['requisition_date']).strftime("%d %b %Y")}</p>
        <p><strong>Note:</strong> {header['requisition_note'] or "—"}</p>

        <table>
            <thead>
                <tr>
                    <th>Description</th>
                    <th>Project</th>
                    <th>Quantity</th>
                </tr>
            </thead>
            <tbody>
    """

    for item in items:
        html += f"""
        <tr>
            <td>{item['description']}</td>
            <td>{item['project']}</td>
            <td>{item['quantity']}</td>
        </tr>
        """

    html += """
            </tbody>
        </table>
        <p style="margin-top: 2rem; font-size: 0.9rem;">Generated by Universal Recycling system</p>
    </body>
    </html>
    """

    # --- Step 3: Generate PDF ---
    pdf_path = OUTPUT_DIR / f"requisition_{requisition_id}.pdf"
    HTML(string=html).write_pdf(str(pdf_path))

    return pdf_path
